Parameters:
  BucketName:
    Description: A name to the s3 bucket
    Type: String

Resources:  
            
  MainBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  MainBucketName:
    Description: Name of the main bucket
    Value: !Ref MainBucket
