apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-backend
spec:
  selector:
    matchLabels:
      app: database-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: database-backend
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.32
        ports:
        - containerPort: 3306
          name: mysql
        envFrom:
          - secretRef:
              name: database-backend-secrets 