apiVersion: v1
kind: Service
metadata:
  labels:
    app: database-backend-svc
  name: database-backend-svc
spec:
  ports:
  - name: database
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: database-backend
  type: ClusterIP