apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
data:
  mysql_db_host: amRiYzpteXNxbDovL2RhdGFiYXNlLWJhY2tlbmQtc3ZjOjMzMDYvd2ViYXBwdXNlcnM=
  mysql_db_pass: WUtkODd1Rm9jbkRBc1BCUlZGWHlGcFdsOWdqMWxGZEE=
  mysql_db_user: YXBwQWNjZXNzREI= 
